replicaCount: 1

port: 3010

version: chat-api-v1

image:
  repository: tokie/chat
  pullPolicy: Always
  tag: latest
  command: [] #ENTRYPOINT
  args: [] #CMD
  containerPort: 3010
  livenessProbe:
    path: /
    port: 3010
    periodSeconds: 30
    successThreshold: 1
    failureThreshold: 3
    timeoutSeconds: 1
  readinessProbe:
    path: /
    port: 3010
    periodSeconds: 30
    successThreshold: 1
    failureThreshold: 3
    timeoutSeconds: 1

strategy:
  rollingUpdate:
    maxSurge: 1
    maxUnavailable: 0

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: false
  annotations: {}
  name: ""

podAnnotations:
  product: chat

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 3010

istio_url: test.ideasoft.io


resources:
  requests:
    cpu: 10m
    memory: 168Mi

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
