apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Release.Name }}-node"
  labels:
    app: "{{ .Release.Name }}-node"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "{{ .Release.Name }}-node"
  template:
    metadata:
      labels:
        app: "{{ .Release.Name }}-node"
    spec:
      initContainers:  # Add an init container
        - name: fetch-s3-data
          image: amazon/aws-cli:latest  # Use an image with AWS CLI
          command:
            - /bin/sh
            - -c
          args:
            - |
              yum install tar gzip -y
              aws s3 cp s3://{{ .Values.s3.bucketName }}/{{ .Values.s3.folderPath }} /home/user/.fhevm-go/keys --recursive
            # aws s3 cp s3://{{ .Values.s3.bucketName }}/{{ .Values.s3.snapshotFilePath }} "/tmp"
            # aws s3 cp s3://{{ .Values.s3.bucketName }}/{{ .Values.s3.snapshotFilePath }} "/root/.arbitrum/Cypher stage/nitro"
            # tar -zxvf "/root/.arbitrum/Cypher stage/nitro/{{ .Values.s3.snapshotFilePath }}"
            # rm -r "/root/.arbitrum/Cypher stage/nitro/{{ .Values.s3.snapshotFilePath }}"
          env:
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: "{{ .Values.s3.secretName }}"
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: "{{ .Values.s3.secretName }}"
                  key: AWS_SECRET_ACCESS_KEY
          volumeMounts:
            - name: fhevm-keys
              mountPath: /home/user/.fhevm-go/keys # Path where files are stored temporarily
            - name: snapshot-data
              mountPath: "/tmp"
          securityContext:
            runAsUser: 0
            runAsGroup: 0
            fsGroup: 1000  
      containers:
        - name: nitro-node
          image: "{{ .Values.node.image }}"
          args:
            - --parent-chain.connection.url={{ .Values.node.parentChainUrl }}
            - --chain.id={{ .Values.node.chainId }}
            - --chain.name={{ .Values.node.chainName }}
            - --http.api={{ .Values.node.httpApi }}
            - --http.corsdomain={{ .Values.node.httpCorsDomain }}
            - --http.addr={{ .Values.node.httpAddr }}
            - --http.vhosts={{ .Values.node.httpVhosts }}
            - --ws.port={{ .Values.node.wsPort }}
            - --ws.addr={{ .Values.node.wsAddr }}
            - --ws.origins={{ .Values.node.wsOrigins }}
            - --execution.forwarding-target={{ .Values.node.executionForwardingTarget }}
            - --node.data-availability.enable
            - --node.data-availability.rest-aggregator.enable
            - --node.data-availability.rest-aggregator.urls={{ .Values.node.dataAvailabilityUrls }}
            - --node.feed.input.url={{ .Values.node.feedInputUrl }}
            - --node.staker.enable={{ .Values.node.stakerEnable }}
            - --node.block-validator.enable={{ .Values.node.blockValidatorEnable }}
            - --node.staker.dangerous.without-block-validator={{ .Values.node.validatorOffEnable }}
            - --chain.info-json=[{"chain-id":46418212302,"parent-chain-id":421614,"parent-chain-is-arbitrum":true,"chain-name":"Cypher stage","chain-config":{"homesteadBlock":0,"daoForkBlock":null,"daoForkSupport":true,"eip150Block":0,"eip150Hash":"0x0000000000000000000000000000000000000000000000000000000000000000","eip155Block":0,"eip158Block":0,"byzantiumBlock":0,"constantinopleBlock":0,"petersburgBlock":0,"istanbulBlock":0,"muirGlacierBlock":0,"berlinBlock":0,"londonBlock":0,"clique":{"period":0,"epoch":0},"arbitrum":{"EnableArbOS":true,"AllowDebugPrecompiles":false,"DataAvailabilityCommittee":true,"InitialArbOSVersion":32,"GenesisBlockNum":0,"MaxCodeSize":24576,"MaxInitCodeSize":49152,"InitialChainOwner":"0x4F88ef7Aa485Fe786A1c9026136d116BdCA87e3A"},"chainId":46418212302},"rollup":{"bridge":"0x2fFD734d02BF46716612150d2Dd70BA7dBf06e7e","inbox":"0xEfA565Ec7997b44c4EB714340A63AA7bdC0404C9","sequencer-inbox":"0xAA35555459Cac7d71e319E890F3c3BAbE6249999","rollup":"0x337F7dcDd42D974635Ac8b002cF4E1b896a17E55","validator-utils":"0x7C100c97a54e2D309a194752Df2f66922A802be3","validator-wallet-creator":"0xFAd2C6Cb969Ab7B18d78BD63e512b650bb70B570","deployed-at":110829945}}]
            - --execution.rpc.evm-timeout={{ .Values.node.evmTimeout }}
            - --execution.caching.database-cache={{ .Values.node.dbCache }}
            - --execution.caching.archive
            # - --init.url=file:///tmp/{{ .Values.s3.snapshotFilePath }}
          ports:
            - name: http
              containerPort: 8547
            - name: websocket
              containerPort: 8548
          volumeMounts:
            - name: arbitrum-data
              mountPath: /home/user/.arbitrum # Path inside the container
            - name: fhevm-keys
              mountPath: /home/user/.fhevm-go/keys
            - name: snapshot-data
              mountPath: "/tmp"
          securityContext:
            runAsUser: 0
            runAsGroup: 0
            fsGroup: 1000
      volumes:
        - name: node-storage
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-node-pvc
        - name: arbitrum-data
          emptyDir: {}
        - name: fhevm-keys
          emptyDir: {}
        - name: snapshot-data
          emptyDir: {}
        
