apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}-node"
  labels:
    app: "{{ .Release.Name }}-node"
spec:
  ports:
    - name: http
      port: 8547
      targetPort: 8547
    - name: websocket
      port: 8548
      targetPort: 8548
  selector:
    app: "{{ .Release.Name }}-node"
