name: Deploy KMS Stack on Production
on:
  push:
    branches:
      - main
    paths:
      - "gateway-v2/cypher-helm-exposed-gateway/**"

jobs:
  rebuild-kms-stack:
    name: Restart KMS stack
    runs-on: ubuntu-20.04
    environment: Development
    timeout-minutes: 30
    steps:
      - name: Build - Git Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.branch }}
      - name: Build - Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2
      - name: Helming
        working-directory: ./gateway-v2/cypher-helm-exposed-gateway
        run: |
          aws eks --region $AWS_REGION update-kubeconfig --name cypher_project-prod
          helm upgrade --install gateway -n kms . -f ./values.yaml
